package com.kp.domain;

public class Knowledge {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column knowledge.kid
     *
     * @mbggenerated
     */
    private Integer kid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column knowledge.user_id
     *
     * @mbggenerated
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column knowledge.cid
     *
     * @mbggenerated
     */
    private Integer cid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column knowledge.status
     *
     * @mbggenerated
     */
    private Integer status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column knowledge.kid
     *
     * @return the value of knowledge.kid
     *
     * @mbggenerated
     */
    public Integer getKid() {
        return kid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column knowledge.kid
     *
     * @param kid the value for knowledge.kid
     *
     * @mbggenerated
     */
    public void setKid(Integer kid) {
        this.kid = kid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column knowledge.user_id
     *
     * @return the value of knowledge.user_id
     *
     * @mbggenerated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column knowledge.user_id
     *
     * @param userId the value for knowledge.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column knowledge.cid
     *
     * @return the value of knowledge.cid
     *
     * @mbggenerated
     */
    public Integer getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column knowledge.cid
     *
     * @param cid the value for knowledge.cid
     *
     * @mbggenerated
     */
    public void setCid(Integer cid) {
        this.cid = cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column knowledge.status
     *
     * @return the value of knowledge.status
     *
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column knowledge.status
     *
     * @param status the value for knowledge.status
     *
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }
}