package com.kp.domain;

import java.util.List;

public class KnowledgeWithBLOBs extends Knowledge {
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column knowledge.title
	 *
	 * @mbggenerated
	 */
	private String title;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column knowledge.content
	 *
	 * @mbggenerated
	 */
	private String content;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column knowledge.extra
	 *
	 * @mbggenerated
	 */
	private String extra;
	
	/**
	 * 此得添加user和category是用于MyBatis中多表联合查询
	 * 通过保存结果到List中前台通过EL表达式取出
	 * e.g 
	 * List xx
	 * ${xx.user.getUserName}
	 * ${xx.category.getCname}
	 */
	private User user;
	private Category category;

	public User getUser() {
		return user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public Category getCategory() {
		return category;
	}

	public void setCategory(Category category) {
		this.category = category;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column knowledge.title
	 *
	 * @return the value of knowledge.title
	 *
	 * @mbggenerated
	 */
	public String getTitle() {
		return title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column knowledge.title
	 *
	 * @param title
	 *            the value for knowledge.title
	 *
	 * @mbggenerated
	 */
	public void setTitle(String title) {
		this.title = title == null ? null : title.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column knowledge.content
	 *
	 * @return the value of knowledge.content
	 *
	 * @mbggenerated
	 */
	public String getContent() {
		return content;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column knowledge.content
	 *
	 * @param content
	 *            the value for knowledge.content
	 *
	 * @mbggenerated
	 */
	public void setContent(String content) {
		this.content = content == null ? null : content.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column knowledge.extra
	 *
	 * @return the value of knowledge.extra
	 *
	 * @mbggenerated
	 */
	public String getExtra() {
		return extra;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column knowledge.extra
	 *
	 * @param extra
	 *            the value for knowledge.extra
	 *
	 * @mbggenerated
	 */
	public void setExtra(String extra) {
		this.extra = extra == null ? null : extra.trim();
	}
}